// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfwgzteslxtqbklywlhb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indmd2d6dGVzbHh0cWJrbHl3bGhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNjUxMzcsImV4cCI6MjA2Njg0MTEzN30.pQjmRV1D5d0aba1fxpzuGiIsSPD44Jj7l77sPrDskT8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});